STATUS_NODE = {
    "1": "AMBIENT_TEMPERATURE_SENSOR",
    "2": "AMBIENT_HUMIDITY_SENSOR",
    "3": "AMBIENT_DIFERERENTIAL_PRESSURE_SENSOR",
    "4":  "PROCESS_PRESSURE_SENSOR",
    "5": "1_CHANEL_AC_5A_CURRENT_SENSOR",
    "6": "2_CHANEL_DIGITAL_INPUT_WITH_CUONTERS",
    "7": "2_CHANEL_DIGITAL_INPUT_WITH_STATUS_DETECTING",
    "8": "2_CHANEL_0-10_VDC_ANALOG_INPUT",
    "9": "1_CHANEL_0-20_mA_ANALOG_INPUT",
    "10": "RELAY_OUTPUT_2_SPDT_OR_4_SPST",
    "11": "SOIL_MOISTURE_SENSOR_WITH_I2C_OUTPUT",
    "12": "SOIL_MOISTURE_SENSOR_WITH_RS485_OUTPUT",
    "255": "NO_SENSOR"
}

BATTERY = {
    '10': "10 %",
    '30': "30 %",
    '60': "60 %",
    '99': "Full Battery"
}
RSSI = {
    "4": "VERY GOOD",
    "3": "GOOD",
    "2": "MEDIUM",
    "1": "BAD"
}
